/**
 * Synthetic User Profiles Seeding Script
 * 
 * Generates 18 realistic synthetic demo user profiles with complete OCEAN score vectors,
 * MUSIC cluster distributions, current moods, and explicit `isSynthetic: true` flags.
 * 
 * Run via: npx tsx scripts/seedSyntheticUsers.ts
 */

import fs from "fs";
import path from "path";
import { SyntheticUser } from "../src/lib/syntheticUsers";

const SYNTHETIC_PROFILES: SyntheticUser[] = [
  {
    id: "synth_user_01",
    name: "Aria Vance",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AriaVance",
    persona: "The Nocturnal Alchemist",
    headline: "Your library weaves atmospheric electronic beats with late-night introspection.",
    isSynthetic: true,
    ocean: { openness: 88, conscientiousness: 52, extraversion: 45, agreeableness: 62, neuroticism: 74 },
    musicClusters: { reflectiveComplex: 55, intenseRebellious: 15, upbeatConventional: 10, energeticRhythmic: 20 },
    currentMood: "Reflective",
    behavioralSignals: { topGenre: "electronic", peakHour: 2, nightListenerRatio: 78, artistLoyalty: 0.45, avgPopularity: 48 },
  },
  {
    id: "synth_user_02",
    name: "Marcus Chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MarcusChen",
    persona: "The High-BPM Energy Driver",
    headline: "You feed on high-tempo house anthems and heavy bass grooves that power your daily drive.",
    isSynthetic: true,
    ocean: { openness: 72, conscientiousness: 65, extraversion: 88, agreeableness: 70, neuroticism: 35 },
    musicClusters: { reflectiveComplex: 15, intenseRebellious: 15, upbeatConventional: 20, energeticRhythmic: 50 },
    currentMood: "Energized",
    behavioralSignals: { topGenre: "house", peakHour: 18, nightListenerRatio: 25, artistLoyalty: 0.38, avgPopularity: 72 },
  },
  {
    id: "synth_user_03",
    name: "Elena Rostova",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ElenaRostova",
    persona: "The Eclectic Audio Curator",
    headline: "An expansive library spanning indie discoveries, bright pop hooks, and cinematic textures.",
    isSynthetic: true,
    ocean: { openness: 94, conscientiousness: 48, extraversion: 76, agreeableness: 82, neuroticism: 40 },
    musicClusters: { reflectiveComplex: 40, intenseRebellious: 10, upbeatConventional: 35, energeticRhythmic: 15 },
    currentMood: "Upbeat",
    behavioralSignals: { topGenre: "indie pop", peakHour: 14, nightListenerRatio: 20, artistLoyalty: 0.30, avgPopularity: 64 },
  },
  {
    id: "synth_user_04",
    name: "Devon Miller",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DevonMiller",
    persona: "The Methodical Rhythm Strategist",
    headline: "Structured ambient soundscapes and steady acoustic rhythms frame your focused daily routine.",
    isSynthetic: true,
    ocean: { openness: 68, conscientiousness: 85, extraversion: 40, agreeableness: 75, neuroticism: 30 },
    musicClusters: { reflectiveComplex: 50, intenseRebellious: 5, upbeatConventional: 35, energeticRhythmic: 10 },
    currentMood: "Calm",
    behavioralSignals: { topGenre: "ambient", peakHour: 20, nightListenerRatio: 35, artistLoyalty: 0.65, avgPopularity: 42 },
  },
  {
    id: "synth_user_05",
    name: "Zoe Sterling",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ZoeSterling",
    persona: "The Intense Distortion Catalyst",
    headline: "Raw post-punk guitars and high-octane alternative rock fuel your rebellious sonic pulse.",
    isSynthetic: true,
    ocean: { openness: 82, conscientiousness: 42, extraversion: 80, agreeableness: 45, neuroticism: 68 },
    musicClusters: { reflectiveComplex: 20, intenseRebellious: 60, upbeatConventional: 5, energeticRhythmic: 15 },
    currentMood: "Fiery",
    behavioralSignals: { topGenre: "post-punk", peakHour: 23, nightListenerRatio: 60, artistLoyalty: 0.42, avgPopularity: 52 },
  },
  {
    id: "synth_user_06",
    name: "Lucas Thorne",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=LucasThorne",
    persona: "The Nocturnal Focus Architect",
    headline: "Late-night synthwave currents and deep electronic focus tracks anchor your after-hours flow.",
    isSynthetic: true,
    ocean: { openness: 85, conscientiousness: 78, extraversion: 38, agreeableness: 58, neuroticism: 62 },
    musicClusters: { reflectiveComplex: 48, intenseRebellious: 22, upbeatConventional: 10, energeticRhythmic: 20 },
    currentMood: "Reflective",
    behavioralSignals: { topGenre: "synthwave", peakHour: 1, nightListenerRatio: 82, artistLoyalty: 0.58, avgPopularity: 55 },
  },
  {
    id: "synth_user_07",
    name: "Sofia Patel",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SofiaPatel",
    persona: "The Harmonious Vocal Aficionado",
    headline: "Silky R&B vocals and accessible melodic arrangements anchor your uplifting afternoon listening.",
    isSynthetic: true,
    ocean: { openness: 70, conscientiousness: 72, extraversion: 74, agreeableness: 91, neuroticism: 28 },
    musicClusters: { reflectiveComplex: 25, intenseRebellious: 5, upbeatConventional: 50, energeticRhythmic: 20 },
    currentMood: "Upbeat",
    behavioralSignals: { topGenre: "r&b", peakHour: 16, nightListenerRatio: 18, artistLoyalty: 0.50, avgPopularity: 78 },
  },
  {
    id: "synth_user_08",
    name: "Julian Kross",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=JulianKross",
    persona: "The Underground Bass Pioneer",
    headline: "Fast drum and bass breakbeats and punchy club tracks drive your high-energy weekend rotation.",
    isSynthetic: true,
    ocean: { openness: 86, conscientiousness: 50, extraversion: 82, agreeableness: 54, neuroticism: 48 },
    musicClusters: { reflectiveComplex: 15, intenseRebellious: 35, upbeatConventional: 10, energeticRhythmic: 40 },
    currentMood: "Fiery",
    behavioralSignals: { topGenre: "drum and bass", peakHour: 22, nightListenerRatio: 52, artistLoyalty: 0.35, avgPopularity: 58 },
  },
  {
    id: "synth_user_09",
    name: "Amara Lawson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AmaraLawson",
    persona: "The Ambient Sanctuary Weaver",
    headline: "Quiet neo-classical piano and minimalist strings create an intimate sanctuary for deep thought.",
    isSynthetic: true,
    ocean: { openness: 90, conscientiousness: 60, extraversion: 32, agreeableness: 85, neuroticism: 55 },
    musicClusters: { reflectiveComplex: 70, intenseRebellious: 5, upbeatConventional: 15, energeticRhythmic: 10 },
    currentMood: "Calm",
    behavioralSignals: { topGenre: "neo-classical", peakHour: 21, nightListenerRatio: 45, artistLoyalty: 0.62, avgPopularity: 38 },
  },
  {
    id: "synth_user_10",
    name: "Gabriel Santos",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=GabrielSantos",
    persona: "The Mainstream Rhythm Enthusiast",
    headline: "Catchy Latin pop hits and vibrant tropical dance tracks keep your everyday energy soaring.",
    isSynthetic: true,
    ocean: { openness: 62, conscientiousness: 68, extraversion: 86, agreeableness: 78, neuroticism: 32 },
    musicClusters: { reflectiveComplex: 10, intenseRebellious: 10, upbeatConventional: 50, energeticRhythmic: 30 },
    currentMood: "Energized",
    behavioralSignals: { topGenre: "latin pop", peakHour: 17, nightListenerRatio: 12, artistLoyalty: 0.40, avgPopularity: 84 },
  },
  {
    id: "synth_user_11",
    name: "Maya Lin",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MayaLin",
    persona: "The Introspective Indie Wanderer",
    headline: "Poetic indie folk lyrics and acoustic warmth capture your reflective, midnight streaming mood.",
    isSynthetic: true,
    ocean: { openness: 87, conscientiousness: 55, extraversion: 42, agreeableness: 72, neuroticism: 66 },
    musicClusters: { reflectiveComplex: 62, intenseRebellious: 12, upbeatConventional: 18, energeticRhythmic: 8 },
    currentMood: "Reflective",
    behavioralSignals: { topGenre: "indie folk", peakHour: 0, nightListenerRatio: 65, artistLoyalty: 0.52, avgPopularity: 50 },
  },
  {
    id: "synth_user_12",
    name: "Kai Takahashi",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=KaiTakahashi",
    persona: "The Experimental Cyberpunk Pulse",
    headline: "Gritty industrial synths and futuristic electronic experiments push your boundary-breaking library.",
    isSynthetic: true,
    ocean: { openness: 96, conscientiousness: 40, extraversion: 68, agreeableness: 38, neuroticism: 70 },
    musicClusters: { reflectiveComplex: 30, intenseRebellious: 50, upbeatConventional: 5, energeticRhythmic: 15 },
    currentMood: "Fiery",
    behavioralSignals: { topGenre: "industrial", peakHour: 3, nightListenerRatio: 88, artistLoyalty: 0.44, avgPopularity: 44 },
  },
  {
    id: "synth_user_13",
    name: "Chloe Bennett",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ChloeBennett",
    persona: "The Melodic Sunshine Listener",
    headline: "Radiant dance pop melodies and uplifting vocal hooks bring bright warmth to your day.",
    isSynthetic: true,
    ocean: { openness: 65, conscientiousness: 75, extraversion: 88, agreeableness: 92, neuroticism: 25 },
    musicClusters: { reflectiveComplex: 10, intenseRebellious: 5, upbeatConventional: 65, energeticRhythmic: 20 },
    currentMood: "Upbeat",
    behavioralSignals: { topGenre: "dance pop", peakHour: 15, nightListenerRatio: 10, artistLoyalty: 0.48, avgPopularity: 82 },
  },
  {
    id: "synth_user_14",
    name: "Oliver Reed",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=OliverReed",
    persona: "The Lo-Fi Chill Explorer",
    headline: "Mellow lo-fi beats and cozy jazz hop samples provide a tranquil backdrop for work and study.",
    isSynthetic: true,
    ocean: { openness: 74, conscientiousness: 80, extraversion: 36, agreeableness: 80, neuroticism: 38 },
    musicClusters: { reflectiveComplex: 45, intenseRebellious: 5, upbeatConventional: 40, energeticRhythmic: 10 },
    currentMood: "Calm",
    behavioralSignals: { topGenre: "lo-fi beats", peakHour: 19, nightListenerRatio: 40, artistLoyalty: 0.56, avgPopularity: 60 },
  },
  {
    id: "synth_user_15",
    name: "Nora Al-Mansoor",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=NoraAlMansoor",
    persona: "The High-Voltage Festival Driver",
    headline: "Pounding EDM drops and stadium electro tracks keep your adrenaline surging past midnight.",
    isSynthetic: true,
    ocean: { openness: 78, conscientiousness: 58, extraversion: 92, agreeableness: 65, neuroticism: 30 },
    musicClusters: { reflectiveComplex: 10, intenseRebellious: 20, upbeatConventional: 20, energeticRhythmic: 50 },
    currentMood: "Energized",
    behavioralSignals: { topGenre: "edm", peakHour: 23, nightListenerRatio: 55, artistLoyalty: 0.32, avgPopularity: 76 },
  },
  {
    id: "synth_user_16",
    name: "Dante Ricci",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DanteRicci",
    persona: "The Darkwave Synthesizer Alchemist",
    headline: "Haunting darkwave basslines and gothic synth layers echo your deep midnight reflections.",
    isSynthetic: true,
    ocean: { openness: 89, conscientiousness: 54, extraversion: 40, agreeableness: 50, neuroticism: 76 },
    musicClusters: { reflectiveComplex: 52, intenseRebellious: 28, upbeatConventional: 5, energeticRhythmic: 15 },
    currentMood: "Reflective",
    behavioralSignals: { topGenre: "darkwave", peakHour: 2, nightListenerRatio: 85, artistLoyalty: 0.60, avgPopularity: 46 },
  },
  {
    id: "synth_user_17",
    name: "Hanna Lindqvist",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=HannaLindqvist",
    persona: "The Acoustic Folk Storyteller",
    headline: "Earthy Nordic folk melodies and organic instrumentation weave a peaceful, grounding atmosphere.",
    isSynthetic: true,
    ocean: { openness: 84, conscientiousness: 72, extraversion: 45, agreeableness: 88, neuroticism: 42 },
    musicClusters: { reflectiveComplex: 60, intenseRebellious: 8, upbeatConventional: 25, energeticRhythmic: 7 },
    currentMood: "Calm",
    behavioralSignals: { topGenre: "nordic folk", peakHour: 20, nightListenerRatio: 30, artistLoyalty: 0.64, avgPopularity: 40 },
  },
  {
    id: "synth_user_18",
    name: "Siddharth Rao",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SiddharthRao",
    persona: "The Cinematic Score Collector",
    headline: "Sweeping orchestral film scores and epic instrumental themes spark your vivid imagination.",
    isSynthetic: true,
    ocean: { openness: 92, conscientiousness: 76, extraversion: 50, agreeableness: 70, neuroticism: 45 },
    musicClusters: { reflectiveComplex: 68, intenseRebellious: 12, upbeatConventional: 10, energeticRhythmic: 10 },
    currentMood: "Reflective",
    behavioralSignals: { topGenre: "soundtrack", peakHour: 22, nightListenerRatio: 50, artistLoyalty: 0.58, avgPopularity: 52 },
  },
];

function seedSyntheticUsers() {
  const targetDir = path.join(__dirname, "../src/data");
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const targetPath = path.join(targetDir, "syntheticUsers.json");
  fs.writeFileSync(targetPath, JSON.stringify(SYNTHETIC_PROFILES, null, 2), "utf-8");

  console.log(`✅ Successfully seeded ${SYNTHETIC_PROFILES.length} synthetic user profiles to ${targetPath}`);
}

seedSyntheticUsers();
